#!/usr/bin/env bash

mkdir -p paraview-build && cd paraview-build
cmake -G"Ninja" -DCMAKE_BUILD_TYPE:STRING=RelWithDebInfo \
  -DCMAKE_INSTALL_LIBDIR:STRING=lib \
  -DCMAKE_FIND_FRAMEWORK:STRING=LAST \
  -DPython3_FIND_STRATEGY:STRING=LOCATION \
  -DPARAVIEW_ENABLE_CATALYST:BOOL=OFF \
  -DPARAVIEW_USE_PYTHON:BOOL=ON \
  -DPARAVIEW_BUILD_WITH_EXTERNAL:BOOL=ON \
  -DPARAVIEW_USE_EXTERNAL_VTK:BOOL=ON \
  -DPARAVIEW_ENABLE_WEB:BOOL=OFF \
  -DPARAVIEW_ENABLE_EMBEDDED_DOCUMENTATION:BOOL=OFF \
  -DPARAVIEW_USE_QTHELP:BOOL=OFF \
  -DPARAVIEW_PLUGINS_DEFAULT:BOOL=OFF \
  -DPARAVIEW_USE_VISKORES:BOOL=OFF \
  ../paraview
ninja
